### ISSUE TITLE
Hovering over an episode tile attempts to load an image, every time

### ISSUE THREAD

**Issue by alexdunncs** [whitefoxllc/expressProject#54]
I suspect this file is the preview image for the video player.  Please investigate and fix.

**Comment by ajcericos** [comment]
> I suspect this file is the preview image for the video player. Please investigate and fix.

Is this still an issue?

**Comment by alexdunncs** [comment]
You'll need to take a look in chrome devtools and check.

**Comment by alexdunncs** [comment]
Complete
