### ISSUE TITLE
User landing page UI mockup

### ISSUE THREAD

**Issue by alexdunncs** [whitefoxllc/expressProject#7]
Mockup required to show layout, functionality and rough style of user landing page, top (logo/search) bar and left menu (user details, navigate by x, blah blah, figure that out)

**Comment by gusep102** [comment]
![sideBarMarkup](https://user-images.githubusercontent.com/43755568/54482896-9f886d80-4807-11e9-9215-b6712e4d0728.png)
sidebar example
![landingSiteMockup](https://user-images.githubusercontent.com/43755568/54482897-9f886d80-4807-11e9-91cb-73d0b855aad8.png)
landing page
![loginPage](https://user-images.githubusercontent.com/43755568/54482898-9f886d80-4807-11e9-9289-2a51f8981def.png)
login


let me know if you need anything changes but i think that should be good for now
